apiVersion: v1
kind: Service
metadata:
  name: fitting-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-fitting-mall.labels" . | nindent 4 }}
    app: fitting-service
spec:
  selector:
    app: fitting-service
  ports:
    - port: {{ .Values.fittingService.port }}
      targetPort: {{ .Values.fittingService.port }}
