apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-fitting-mall.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.password | b64enc | quote }}
  spring-datasource-password: {{ .Values.mysql.password | b64enc | quote }}
