apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-fitting-mall.labels" . | nindent 4 }}
    app: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - port: {{ .Values.gateway.port }}
      targetPort: {{ .Values.gateway.port }}
